const { ethers, upgrades } = require('hardhat');

// TO DO: Place the address of your proxy here!
const proxyAddress = '0x410bF7e2849e5ff00CcC394B128714fF41Eab597';

async function main() {
  const VendingMachineV3 = await ethers.getContractFactory('VendingMachineV3');  // Get the contract factory for the 'VendingMachineV3' contract.
  const upgraded = await upgrades.upgradeProxy(proxyAddress, VendingMachineV3);  // Upgrade the proxy contract at 'proxyAddress' to the new implementation contract generated by the 'VendingMachineV3' factory.

  const implementationAddress = await upgrades.erc1967.getImplementationAddress(
    proxyAddress
  );  // Retrieve the address of the implementation contract associated with the proxy contract at 'proxyAddress'.

  console.log("The current contract owner is: " + upgraded.owner());  // Print the address of the current owner of the upgraded contract.
  console.log('Implementation contract address: ' + implementationAddress);  // Print the address of the implementation contract.
}

main();  // Call the 'main' function to execute the upgrade and retrieve information about the contract.
